# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92dcb89c7af823d6f619ba9c03ea5fbfd27d54ca53ca9df1e08958b0722ee1a3391821d37e7ef3f90620c1551623784503832a726cc34b722d8da0530a448e0f

test:
  secret_key_base: 6a5e56dc0a5025b128681dd204dc9ff3443926ba84e8d29bb1363581b0f80cb2e5decd15e8fcf349a1917ad74c595501e2f00c4a33c9a37770c50054a3c318ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
